%YAML:1.0
calibrate: 1
folder: "new"
alpha: 0
showRectified: 0
drawROI: 0
enableDisparity: 1
minDisparity: 0
numDisparities: 320
SADWindowSize: 5
disparitySmoothness1: 2312
disparitySmoothness2: 9248
